from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import JSONB_TYPE, TimestampMixin


class ProcurementRecommendation(TimestampMixin, Base):
    """Recommended procurement action generated by the orchestrator."""

    __tablename__ = "procurement_recommendations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    scenario_id: Mapped[int | None] = mapped_column(
        ForeignKey("scenarios.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    refinery_id: Mapped[int | None] = mapped_column(
        ForeignKey("refineries.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(220), nullable=False, index=True)
    recommended_supplier: Mapped[str] = mapped_column(String(220), nullable=False, index=True)
    recommended_route: Mapped[str] = mapped_column(String(220), nullable=False, index=True)
    expected_cost_delta: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    risk_reduction_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    compatibility_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    action_priority: Mapped[str] = mapped_column(String(32), nullable=False, default="medium")
    recommendation_payload: Mapped[dict] = mapped_column(JSONB_TYPE, nullable=False, default=dict)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )

    scenario = relationship("Scenario", back_populates="recommendations")
    refinery = relationship("Refinery", back_populates="recommendations")


class SPRPlan(TimestampMixin, Base):
    """Strategic Petroleum Reserve drawdown and replenishment plan."""

    __tablename__ = "spr_plans"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    scenario_id: Mapped[int | None] = mapped_column(
        ForeignKey("scenarios.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    total_drawdown_bbl: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    drawdown_days: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    daily_release_schedule: Mapped[dict] = mapped_column(JSONB_TYPE, nullable=False, default=dict)
    replenishment_strategy: Mapped[dict] = mapped_column(JSONB_TYPE, nullable=False, default=dict)
    policy_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )

    scenario = relationship("Scenario", back_populates="spr_plan")
