"""Pydantic schemas for the backend application."""

from app.schemas.auth import CurrentUserResponse, LoginRequest, TokenResponse, UserCreate
from app.schemas.domain import (
    AuditLogResponse,
    CommodityPriceResponse,
    GeopoliticalEventResponse,
    PortResponse,
    RefineryResponse,
    RiskScoreResponse,
    SanctionsEventResponse,
    ShipmentResponse,
    ShippingCorridorResponse,
    SupplierCountryResponse,
)
from app.schemas.scenario import (
    ScenarioAssumptions,
    ScenarioCreateRequest,
    ScenarioListItemResponse,
    ScenarioRefineryImpact,
    ScenarioResponse,
    ScenarioResultResponse,
    ScenarioResultsEnvelopeResponse,
    ScenarioRunRequest,
    ScenarioSimulationResponse,
)
from app.schemas.procurement import (
    ProcurementOptionResponse,
    ProcurementRecommendRequest,
    ProcurementRecommendResponse,
    ProcurementRecommendationListResponse,
    ProcurementRecommendationResponse,
    ProcurementScope,
)
from app.schemas.map import GeoJSONFeature, GeoJSONFeatureCollection, GeoJSONGeometry, MapNetworkResponse
from app.schemas.spr import (
    SPRDailyReleaseResponse,
    SPRPlanListResponse,
    SPRPlanResponse,
    SPRRefineryAllocationResponse,
    SPROptimizeRequest,
    SPROptimizeResponse,
)

__all__ = [
    "AuditLogResponse",
    "CommodityPriceResponse",
    "CurrentUserResponse",
    "GeopoliticalEventResponse",
    "LoginRequest",
    "PortResponse",
    "ProcurementOptionResponse",
    "ProcurementRecommendationResponse",
    "ProcurementRecommendRequest",
    "ProcurementRecommendResponse",
    "ProcurementRecommendationListResponse",
    "ProcurementScope",
    "GeoJSONFeature",
    "GeoJSONFeatureCollection",
    "GeoJSONGeometry",
    "MapNetworkResponse",
    "RefineryResponse",
    "RiskScoreResponse",
    "SanctionsEventResponse",
    "ScenarioAssumptions",
    "ScenarioCreateRequest",
    "ScenarioListItemResponse",
    "ScenarioRefineryImpact",
    "ScenarioResponse",
    "ScenarioResultResponse",
    "ScenarioResultsEnvelopeResponse",
    "ScenarioRunRequest",
    "ScenarioSimulationResponse",
    "ShipmentResponse",
    "ShippingCorridorResponse",
    "SPROptimizeRequest",
    "SPROptimizeResponse",
    "SPRDailyReleaseResponse",
    "SPRPlanListResponse",
    "SPRPlanResponse",
    "SPRRefineryAllocationResponse",
    "SupplierCountryResponse",
    "TokenResponse",
    "UserCreate",
]
